<?php
session_start();
unset($_SESSION["memName"]);
unset($_SESSION["memEmail"]);
unset($_SESSION["memNo"]);
unset($_SESSION["letCount"]);
unset($_SESSION["airCoin"]);
unset($_SESSION["intColor"]);
unset($_SESSION["matPosUrl"]);
